name: AutoInventory
main: io.AutoInventory.AutoInventory
author: nbpe
version: 1.2.0
api: ["1.0.9"]
description: AutoInventory for NukkitX
commands:
   dropwhenfull:
      description: When a player's inventory is full, do mined blocks drop or destroy? Default is to drop.
      usage: "/dropwhenfull"
      permission: AutoInventory.op
      permission-message: You don't have <permission>
   autoinventory:
      description: Choose if players can toggle AutoInv [CanChoose], and toggle it for the server [All].
      usage: "/autoinventory [CanChoose/All]"
      permission: AutoInventory.op
      permission-message: You don't have <permission>
   autoinv:
      description: Allow players to toggle AutoInventory for themselves.
      usage: "/autoinv"