name: AutoInventory
main: io.AutoInventory.AutoInventory
author: nbpe
version: 1.0.7
api: ["1.0.0"]
description: AutoInventory for NukkitX
softdepend: ["Residence"]
commands:
   dropwhenfull:
      description: When a player's inventory is full, do mined blocks drop or destroy? Default is to drop.
      usage: /dropwhenfull
      permission: AutoInventory.op
      permission-message: You don't have <permission>